language: python
python:
  - "3.6"

sudo: false
cache: pip
dist: trusty

install: 
  - pip3 install sphinx
  - pip3 install sphinx_rtd_theme

script:
  - install.sh -d
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  target_branch: gh-pages
  local_dir: docs/_build/html
